config/routes.rb
Rails.application.routes.draw do
  get 'finder' => 'finders#finder'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books, only:[:create,:index,:show,:edit,:update,:destroy] do
    resource :likes, only: [:create, :destroy]
    resources :book_comments, only: [:create,:destroy]
  end
  resources :users, only: [:show,:index,:edit,:update,:create,:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :book_comments, dependent: :destroy
  
  validates :title , presence: true
  validates :body , length: {maximum: 200}, presence: true
  
  def self.looks(searches, words)
    if searches == "perfect_match"
      @book = Book.where("title LIKE ?", "#{words}")
    elsif searches == "forward_match"
      @book = Book.where("title LIKE ?", "#{words}%")
    elsif searches == "backword_match"
      @book = Book.where("title LIKE ?", "#{words}")
    else
      @book = Book.where("title LIKE ?", "%#{words}%")
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  validates :content , presence: true
  belongs_to :user
  belongs_to :book
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :book_comments, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, length: {minimum: 2,maximum: 20} , uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    elsif searches == "forward_match"
      @user = User.where("name LIKE ?", "#{words}%")
    elsif searches == "backword_match"
      @user = User.where("name LIKE ?", "#{words}")
    else
      @user = User.where("name LIKE ?", "%#{words}%")
    end
  end

  def already_liked?(book)
    self.likes.exists?(book_id: book.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top , :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book_comment = current_user.book_comments.new(comment_params)
    if @book_comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @book_comment = BookComment.find_by(params[:id], user_id: current_user.id)
    @book_comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def comment_params
    params.require(:book_comment).permit(:content, :book_id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :baria_book , only: [:edit]

  def create
    @user = current_user
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
        redirect_to book_path(@book.id), notice:'You have created book successfully.'
    else
       render"index"
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
    @like = Like.new
  end

  def show
    @book = Book.new
    @user_book = Book.find(params[:id])
    @user = @user_book.user
    @like = Like.new
    @book_comments = @user_book.book_comments.all
    @book_comment = current_user.book_comments.new
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id),notice:"You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

   private

   def book_params
     params.require(:book).permit(:title,:body)
   end

   def baria_book
     unless Book.find(params[:id]).user_id == current_user.id
     Book.find(params[:id]).user_id =! current_user.id
     redirect_to books_path
     end
   end

end

app/controllers/finders_controller.rb
class FindersController < ApplicationController
  def finder
    @range = params[:range]
    
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
 def top
 end
 def about
 end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
    @like = current_user.likes.create(book_id: params[:book_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(book_id: params[:book_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :baria_user, only: [:edit]
  
  def show
    @book = Book.new
    @user_book = Book.where(user_id:params[:id])
    @user = User.find(params[:id])
  end
  
  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice:"You have updated user successfully."
    else
      render"edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end
  
  def baria_user
    unless User.find(params[:id]).id == current_user.id
    # if User.find(params[:id]).id != current_user.id 
    redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/finders_helper.rb
module FindersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class ="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <div id="error_explanation" >
          <h3><%= @book.errors.count%>errors prohibited this obj from being saved:</h3><br>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li> <%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model:@book,local:true do |f| %>
      
        <div class="form-group">
          <label for="book-title">Title</label>
          <%= f.text_field :title , class:"form-control book_title" %>
        </div>
        
        <div class="form-group">
          <label for="book-opinion">Opinion</label>
          <%= f.text_area :body , class:"form-control book_body" %>
        </div>
        
        <div class="form-group">
          <%= f.submit'Update Book',class:"btn btn-success" %>
        </div>
        
      <% end %>
      
      <%= link_to "Show" , book_path(@book.id)%>
      |
      <%= link_to "Back" , books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation" >
    <h3><%= @book.errors.count%>errors prohibited this obj from being saved:</h3><br>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li> <%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class ="container px-5 px-sm-0">
  <div class="row">
    <%=render'users/list',user:@user,book:@book %>
    <div class ="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
      <therd>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan=3></th>
        </tr>
      </therd>
      <% @books.each do |book| %>
        <tbody>
          <tr>

            <td>
            <%= link_to user_path(book.user.id) do %>
            <%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg"%>
            <% end %>
            </td>

            <td>
              <%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
            </td>

            <td>
              <%= book.body %>
            </td>

            <td>
              <% if current_user.already_liked?(book) %>
                <%= link_to book_likes_path(book), method: :delete do %>
                <i class="fas fa-heart"><%= book.likes.count %></i>
                <% end %>
              <% else %>
                <%= link_to book_likes_path(book), method: :post do %>
                <i class="far fa-heart"><%= book.likes.count %></i>
                <% end %>
              <% end %>
            </td>
          </tr>
        </tbody>
      <% end %>
     </table>
   </div>
 </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'users/list',user:@user,book:@book%>
    <div class ="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>

            <td>
              <%=link_to user_path(@user.id) do %>
              <%= attachment_image_tag @user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %><br>
              <%=@user.name %>
              <% end %>
            </td>

            <td>
              <%=link_to book_path(@user_book.id) do%>
              <%=@user_book.title %>
              <% end %>
            </td>

            <td>
              <%= @user_book.body %>
            </td>

            <% if @user_book.user == current_user %>

            <td>
              <%=link_to edit_book_path(@user_book.id) ,class:"btn btn-sm btn-success" do %>
              Edit
              <% end %>
            </td>

            <td>
              <%=link_to book_path(@user_book.id), method: :delete ,class:"btn btn-sm btn-danger " ,method: :delete, data: {confirm: "本当に消しますか？"}  do%>
              Destroy
              <% end %>
            </td>
            <% end %>
            <td>
              <% if current_user.already_liked?(@user_book) %>
                <%= link_to book_likes_path(@user_book), method: :delete do %>
                <i class="fas fa-heart"><%= @user_book.likes.count %></i>
                <% end %>
              <% else %>
                <%= link_to book_likes_path(@user_book), method: :post do %>
                <i class="far fa-heart"><%= @user_book.likes.count %></i>
                <% end %>
              <% end %>
            </td>

          </tr>
        </tbody>
      </table>
      <table>
      <% @book_comments.each do |comment| %>
        <tbody>
          <tr>
            <td>
              <%=link_to user_path(comment.user.id) do %>
              <%= attachment_image_tag comment.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %><br>
              <%=comment.user.name %>
              <% end %>
            </td>

            <td>
              <%= comment.content %>
            </td>

            <td>
              <%= link_to "Destroy", book_book_comment_path(@user_book), method: :delete ,class:"btn btn-danger"%>
            </td>
          </tr>
        </tbody>
      <% end %>
      </table>
        <% unless current_user == @user_book.user %>
        <%= form_with model: [@user_book , @book_comment], method: :post do |f| %>
          <%= f.text_area :content ,class:"form-control" %>
          <%= f.hidden_field :book_id, value: @user_book.id %>
          <%= f.submit '送信',class:"mt-1" %>
        <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/finders/finder.html.erb
<% if @range == "User" %>
  <% @users.each do |user| %>
    <%= user.name %>
  <% end %>
<% else %>
  <% @books.each do |book| %>
    <%= book.title%>
  <% end %>
<% end %>

app/views/homes/about.html.erb
 <div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class ="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
      <p>In<i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in" , new_user_session_path , class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign up" , new_user_registration_path , class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "Bookers" , root_path ,class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class= "navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to "Home", user_path(current_user.id) ,class: 'fas fa-home nav-link text-light' %>
          </li>
          <li>
            <%= link_to "User" , users_path ,class: 'fas fa-users nav-link text-light' %>
          </li>
          <li>
            <%= link_to "Books" , books_path , class: 'fas fa-book-open nav-link text-light' %>
          </li>
          <li>
            <%= link_to "logout" , destroy_user_session_path, class: 'fas fa-sign-out-alt nav-link text-light' , method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path , class: 'fas fa-home nav-link text-light' do %>Home<% end %>
          </li>
          <li>
            <%= link_to home_about_path , class: 'fas fa-link nav-link text-light' do %>About<% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path , class: 'fas fa-user-plus nav-link text-light' do %>sign up<% end %>
          </li>
          <li>
            <%= link_to new_user_session_path , class: 'fas fa-sign-in-alt nav-link text-light' do %>login<% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<!--検索機能-->
<%= form_with url: finder_path, method: :get, local: :true do  |f| %>
  <%= f.select :range, options_for_select( [ ['User'],['Book'] ] ) %>
  <%= f.select :search, options_for_select( [ ["完全一致" , "perfect_match"], ["部分一致" , "partial_match"],["前方一致", "forward_match"],["後方一致" , "backword_match" ] ] ) %>
  <%= f.text_field :word %>
  <%= f.submit "検索" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>
  <body>
    <header>

     <%= render 'layouts/header' %>

    </header>
    <main>
      <p id="notice">
         <%= flash[:notice] %>
      </p>
      <%= yield %>
    </main>
    <footer>
      <div class = "container mt-5">
        <div class ="row">
          <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
<div class ="col-md-3">
  <h2>User info</h2>
  
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  
  <div class="row">
    <%= link_to edit_user_path(user.id),class:"btn btn-outline-secondary btn-block" do %>
    <i class ="fas fa-user-cog"></i>
    <% end %>
  </div>
  
  <h2 class="mt-3">New book</h2>
  <%= form_with model:book,local:true do |f| %>
  
    <div class="form-group">
      <label for="book-title">Title</label>
      <%= f.text_field :title , class:"form-control book_title" %>
    </div>
    
    <div class="form-group">
      <label for="book-opinion">Opinion</label>
      <%= f.text_area :body , class:"form-control book_body" %>
    </div>
    
    <div class="form-group">
      <%= f.submit'Create Book' , class: "btn btn-success" %>
    </div>
    
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class ="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info </h2>
      <% if @user.errors.any? %>
        <div id="error_explanation" >
          <h3><%= @user.errors.count%>errors prohibited this obj from being saved:</h3><br>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li> <%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model:@user,local:true do |f| %>
      
        <div class="form_group">
          <%= f.label :name %><br />
          <%= f.text_field :name, autofocus:true, autocomplete:"name" ,class:"form-control name" %>
        </div>
        
        <div class="form_group">
          <%= f.label :profile_image %><br />
          <%= f.attachment_field :profile_image ,class:"form-control-file user_image" %>
        </div>
      
        <div class="form_group">
          <%= f.label :introduction %><br />
          <%= f.text_area :introduction, autofocus:true, autocomplete:"introduction",class:"form-control introduction" %>
        </div>
      
        <div class="form_group">
          <%= f.submit "Update User" ,class:"btn btn-secondary" %>
        </div>
        
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class ="container px-5 px-sm-0">
  <div class="row">
    <%= render 'list',user:@user,book:@book %>
    <div class ="col-md-8 offset-md-1">
      
      <h2>Users</h2>
      
      <table class ="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan =3></th>
          </tr>
        </thead>
        
        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td> <%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %> </td>
            <td> <%= user.name %> </td>
            <td>
              <%=link_to "Show" ,user_path(user.id)  %>
            </td>
          </tr>
        </tbody>
        <% end %>
        
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class ="container px-5 px-sm-0">
  <div class="row">
    <%= render'list',user:@user,book:@book %>
    <div class ="col-md-8 offset-md-1">
      
      <h2>Books</h2>
      
      <table class ="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan=3></th>
          </tr>
        </thead>
        
       <% @user_book.each do|book| %>
        <tbody>
          <tr>
            
           <td>
             <%=link_to user_path(book.user.id) do %>
             <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg" ,size: "40x40"%>
             <% end %>
           </td>
           
           <td>
             <%=link_to book_path(book.id) do %>
             <%=book.title %>
             <% end %>
           </td>
           
           <td>
             <%= book.body %>
           </td>
           
           </tr>
        </tbody>
       <% end %>
      </table>
    </div>
  </div>
</div>